"""constructor in PatientPublic model

Revision ID: c5f17cf68277
Revises: e2d29e2009ea
Create Date: 2025-03-10 17:50:02.963886

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5f17cf68277'
down_revision = 'e2d29e2009ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
