""" patient model

Revision ID: 84024f8e14c9
Revises: c64f5eead671
Create Date: 2025-03-09 09:53:02.930419

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84024f8e14c9'
down_revision = 'c64f5eead671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
