"""PatientBase model update 

Revision ID: ac4cb8eb7adf
Revises: e1700df0d6eb
Create Date: 2025-03-06 17:45:18.247386

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac4cb8eb7adf'
down_revision = 'e1700df0d6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'email',
               existing_type=sa.VARCHAR(length=55),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'email',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.VARCHAR(length=55),
               existing_nullable=False)
    # ### end Alembic commands ###
