"""PatientBase model update 

Revision ID: ac943022af9c
Revises: 32ba675b8ec6
Create Date: 2025-03-06 17:01:03.321651

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ac943022af9c'
down_revision = '32ba675b8ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
