"""PatientBase model update 

Revision ID: b21c8ff93010
Revises: ac943022af9c
Create Date: 2025-03-06 17:11:25.964093

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b21c8ff93010'
down_revision = 'ac943022af9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
