"""add birth date column for patient model

Revision ID: c64f5eead671
Revises: 5440ba268ff9
Create Date: 2025-03-08 15:15:42.887375

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c64f5eead671'
down_revision = '5440ba268ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('birth_date', sa.TIMESTAMP(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'birth_date')
    # ### end Alembic commands ###
