"""PatientBase model update 

Revision ID: e1700df0d6eb
Revises: b21c8ff93010
Create Date: 2025-03-06 17:27:07.734885

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e1700df0d6eb'
down_revision = 'b21c8ff93010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
