""" patient model2

Revision ID: f3ed4262a7d7
Revises: ee67961fce07
Create Date: 2025-03-09 09:56:43.189377

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f3ed4262a7d7'
down_revision = 'ee67961fce07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
